---
title: "HW 4"
author: "Bryan Mui - UID 506021334"
date: "2025-03-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("506021334_stats102a_hw4.R")
```


# Part 1: Dealing with Large Numbers 

## 1a)

```{r error_handling_demonstration}
# e1 <- pqnumber(5, 5, 5, c())
# e1 <- pqnumber(1, 5.5, 5, c())
# e1 <- pqnumber(1, 5, 5.5, c())
# e1 <- pqnumber(1, 5, 5, c(1, 2))
# e1 <- pqnumber(1, 1, 1, c(1, 2, 3.1))
```


```{r}
options(digits = 10)
n1 <- pqnumber(1, 3, 4, c(1, 2, 3, 4, 5, 6, 7, 8))
n2 <- pqnumber(1, 6, 0, c(3, 9, 5, 1, 4, 1, 3))
n3 <- pqnumber(-1, 5, 1, c(2, 8, 2, 8, 1, 7, 2))
is_pqnumber(n1)
is_pqnumber(1)
print(n1, DEC=TRUE)
print(as_numeric(n2))
print(as_numeric(n3))
print(as_pqnumber(-12343.141, p = 3, q = 4), DEC=TRUE)
```


## 1b) Addition and Subtraction

```{r}
n1 <- pqnumber(1, 3, 4, c(1, 2, 3, 4, 5, 6, 7, 8))
n2 <- pqnumber(1, 6, 0, c(3, 9, 5, 1, 4, 1, 9))

# add(n1, n2)
print(n1, DEC = TRUE)
print(n2, DEC = TRUE)
# align_pqnumber(n1, 6, 5)
# align_pqnumber(n2, 6, 5)
print(add(n1, n2), DEC = TRUE)
```

## part c) Multiplication

```{r}
print(multiply(n1, n2), DEC = TRUE)
```

