---
title: "HW 4"
author: "Bryan Mui - UID 506021334"
date: "2025-03-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# REMEMBER TO MOVE RMD CODE TO R FILE

# Part 1: Dealing with Large Numbers 

## 1a)

```{r}
# constructor function
pqnumber <- function(sign, p, q, nums) {
  if(sign != 1 && sign != -1) {
    stop("Sign needs to be either -1 or 1")
  } else if(p %% 1 != 0) {
    stop("p needs to be an integer")
  } else if(q %% 1 != 0) {
    stop("q needs to be an integer")
  } else if(length(nums) != (p + q + 1) || sum(nums %% 1 != 0)) {
    stop("nums vector needs to be length p+q+1 and all values in nums have to be between 1-8")
  }
  return(structure(list(sign = sign, p = p, q = q, nums = nums), class="pqnumber"))
}

# predicate function
is_pqnumber <- function(x) {
  if(inherits(x, "pqnumber")) {
    return(TRUE)
  }
  return(FALSE)
}

# helper function
to_decimal <- function(x) {
  if(!is_pqnumber(x)) {
    stop("object needs to be a pq number!")
  }
  power <- x$p * -1
  decimal <- 0
  # for every number, multiplied by the power in ascending order 
  for(i in x$nums) {
    decimal <- decimal + (i * 10^power)
    power <- power + 1
  }
  # return the result multiplied by sign
  return(decimal * x$sign)
}

# print() method
print.pqnumber <- function(x, DEC=FALSE) {
  if(DEC) {
    cat(to_decimal(x), "\n")
  }
  cat("sign = ", x$sign, "\n")
  cat("p = ", x$p, "\n")
  cat("q = ", x$q, "\n")
  cat("nums = ", x$nums, "\n")
}

# coercion functions
as_pqnumber <- function(x, p, q) {
  if(x < 0) {
    sign <- -1
  } else {
    sign <- 1
  }
  x <- x * 10^p
  print(x)
  vec <- as.numeric(unlist(strsplit(as.character(abs(x)), "")))

  # reverse the list
  start <- 1
  end <- length(vec)
  while(start < end) {
    # swap the components
    temp <- vec[start]
    vec[start] <- vec[end]
    vec[end] <- temp
    start <- start + 1
    end <- end - 1
  }
  
  while(length(vec) < p + q + 1) {
    vec[length(vec) + 1] <- 0
  }
  
  pqnumber(sign = sign, p = p, q = q, nums = vec)
}

as_numeric <- function(x) {
  return(to_decimal(x))
}
```

```{r error_handling_demonstration}
# e1 <- pqnumber(5, 5, 5, c())
# e1 <- pqnumber(1, 5.5, 5, c())
# e1 <- pqnumber(1, 5, 5.5, c())
# e1 <- pqnumber(1, 5, 5, c(1, 2))
# e1 <- pqnumber(1, 1, 1, c(1, 2, 3.1))
```


```{r}
options(digits = 10)
n1 <- pqnumber(1, 3, 4, c(1, 2, 3, 4, 5, 6, 7, 8))
n2 <- pqnumber(1, 6, 0, c(3, 9, 5, 1, 4, 1, 3))
n3 <- pqnumber(-1, 5, 1, c(2, 8, 2, 8, 1, 7, 2))
is_pqnumber(n1)
is_pqnumber(1)
print(n1, DEC=TRUE)
print(as_numeric(n2))
print(as_numeric(n3))
print(as_pqnumber(-12343.141, p = 3, q = 4), DEC=TRUE)
```


```{r dump}
nums <- c(1, 2, 3, 4, 5.5, 6)
print(sum(nums %% 1 != 0))
as.character(-3.14)
```

## 1b) Addition and Subtraction

```{r}
n1 <- pqnumber(1, 3, 4, c(1, 2, 3, 4, 5, 6, 7, 8))
n2 <- pqnumber(1, 6, 0, c(3, 9, 5, 1, 4, 1, 3))
add <- function(x, y) {
  integer_max <- as.integer(2^31-1)
  q_max <-max(x$q, y$q) + 1
  p_max <- max(x$p, y$p)
  print(p_max)
  print(q_max)
}
```

```{r}
add(n1, n2)
print(n1, DEC = TRUE)
print(n2, DEC = TRUE)
print()
```

