---
title: "506021334 Stats102A HW1"
author: "Bryan Mui"
date: "2025-01-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sourcing the R file(file should be within the working directory)

```{r source}
source("./506021334_stats102a_hw1.R")
```

## Test Cases

### Problem 1

#### Function: gcd()

```{r gcd}
# Error handling test case
gcd(12.2, 14.9) # Coerce to integers
gcd("TRUE", FALSE) # NULL
# in class test cases
gcd(48, 18L) # 6
gcd(180, 25L) # 5
gcd(-42112, 56399) # 7
```
#### Function: gcdi()

```{r gcdi}
# Error handling test cases
gcdi(c(4.2, 4.5, 124L)) # 4
gcdi(list("TRUE", 1, 2.6, FALSE)) # NULL
gcdi(c(2.2, 9.6, "HELLO")) # NULL
# in class test cases
gcdi(c(16, 32, -58)) # 2
gcdi(c(4789, 6123, 19927334)) # 1
```

### Problem 2

#### Function: lcm()

```{r lcm}
# Error handling test case
lcm("HELLO", "WORLD") # NULL
lcm(148.9, 3452.123456) # 127,724, coerces by removing the decimal(rounding down)
# in class test cases
lcm(4, 6) # 12
lcm(123, 4920) # 4920
lcm(8675309, 9876543) # ~8.5682062377 * 10^13
```

#### Function: add_2_frac()

```{r add_2_frac}
# Error handling test case
add_2_frac(1.1, FALSE, 1, 3) # NaN
# in class test cases
add_2_frac(1, 2, 1, 3) # 5/6
add_2_frac(1, 11, 1, 5) # list(num = 16, denom = 55)
add_2_frac(1, 11, -1, 5) # list(num = -6, denom = 55)
add_2_frac(2468, 3579, 1357, 2468) # 10947727 / 8832972
```

### Problem 3

#### Function: is_prime()

```{r is_prime}
# Error handling test case
is_prime(c(TRUE, "FALSE", NA, 48, 1.2, 3L)) # NULL
# in class test cases
is_prime(c(9, 7)) # [False True]
is_prime(c(1, 3, 5)) # [FALSE TRUE TRUE]
is_prime(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) # [FALSE TRUE TRUE FALSE TRUE FALSE TRUE FALSE FALSE FALSE]
is_prime(c(29, 97, 143, 169, 221, 323, 377, 493, 541, 599)) # [TRUE TRUE FALSE FALSE FALSE FALSE FALSE FALSE TRUE TRUE]
```

#### Function: get_factors()

```{r get_factors}
# Error handling test case
get_factors(1.92) # appropriate error handling: NULL
get_factors(377.777)  # primes = [13 29] exponents [1 1]
# in class test cases
x <- sample(x = 1e4, size = 1)
y <- get_factors(x)
this_works <- prod(y$primes^y$exponents) == x & all(is_prime(y$primes))
if (this_works) {
  print("passed test case!")
} else {print("false!")}
# other test cases
get_factors(1920) # list(primes = [2 3 5], exponents = [7 1 1])
print(get_factors(1532512)) # list(primes = [2 83 577], exponents = [5 1 1])
```

